[AEG-4714] Update to new SDK
jamf/Subprocess pull request #9
Opened 2022-08-19 06:07 UTC by Saczuu

Update a MockProcess so it will build on newest macos.

2022-09-06 22:20 UTC, grandoracle requested changes

2022-09-06 22:20 UTC, grandoracle commented on Sources/SubprocessMocks/MockProcess.swift
> +        var terminationHandler: (@Sendable (Process) -> Void)?
To support building against earlier versions of Foundation, I believe adopting the following will help.

```
#if compiler(>=5.7)
        var terminationHandler: (@Sendable (Process) -> Void)?
#else
        var terminationHandler: ((Process) -> Void)?
#endif
```

It is not a pretty way to do things as we really need to know the version of Foundation, but my research indicates this is the closest way to do as of earlier this year.

2022-09-06 22:20 UTC, grandoracle commented on Sources/SubprocessMocks/MockProcess.swift
> +    open override var terminationHandler: (@Sendable (Process) -> Void)? {
Similar to above, might I suggest using:

```
#if compiler(>=5.7)
    open override var terminationHandler: (@Sendable (Process) -> Void)? {
        get { context.terminationHandler }
        set { context.terminationHandler = newValue }
    }
#else
    open override var terminationHandler: ((Process) -> Void)? {
        get { context.terminationHandler }
        set { context.terminationHandler = newValue }
    }
#endif
```

2022-09-08 13:38 UTC, grandoracle approved these changes
Looks good.

2022-09-08 23:50 UTC, cyrusingraham approved these changes

2022-09-09 09:03 UTC, merged